version: '2.1'

services:
  migration:
    image: node:8-alpine
    command: /usr/app/node_modules/.bin/knex migrate:latest
    working_dir: /usr/app/src/adapters/knex
    volumes:
      - ./src/adapters/knex:/usr/app/src/adapters/knex
      - ./node_modules/.bin/knex:/usr/app/node_modules/.bin/knex
    environment:
      DATABASE_PORT: 3306
      DATABASE_HOST: mysql
      DATABASE_NAME: test
      DATABASE_USER: root
      DATABASE_PASSWORD: root
      DATABASE_POOL_MIN: 1
      DATABASE_POOL_MAX: 10
      REDIS_URL: redis://redis_db:6379
      SCORE_PERIOD_CONFIG: '[{"id":"day","duration":86400000},{"id":"week","duration":604800000}]'
    depends_on:
      mysql:
        condition: service_healthy
  mysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: test
      MAX_CONNECTIONS: 8192
    ports:
      - 9906:3306
    healthcheck:
      test: '/usr/bin/mysql --user=root --password=root --execute "SHOW DATABASES";'
      timeout: 5s
      retries: 12
  redis_db:
    image: redis:5.0
    ports:
      - 9907:6379
