version: '3'

services:
  node:
    build: .
    volumes:
      - .:/usr/app:cached
    environment:
      DATABASE_PORT: 3306
      DATABASE_HOST: mysql
      DATABASE_NAME: test
      DATABASE_USER: root
      DATABASE_PASSWORD: root
      DATABASE_POOL_MIN: 1
      DATABASE_POOL_MAX: 10
      REDIS_URL: redis://redis_db:6379
      SCORE_PERIOD_CONFIG: '[{"id":"day","duration":86400000},{"id":"week","duration":604800000}]'
    depends_on:
      - mysql
      - redis_db
  mysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: test
      MAX_CONNECTIONS: 8192
    ports:
      - 9906:3306
  redis_db:
    image: redis:5.0
