version: '3'

services:
  node:
    build: .
    volumes:
      - .:/usr/app:cached
    environment:
      DATABASE_PORT: 3306
      DATABASE_HOST: mysql
      DATABASE_NAME: test
      DATABASE_USER: root
      DATABASE_PASSWORD: root
      DATABASE_POOL_MIN: 1
      DATABASE_POOL_MAX: 1
    depends_on:
      - mysql
  mysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: test
    ports:
      - 3306:3306
