version: '2.3'

services:
  tests:
    build:
      context: .
      dockerfile: test.Dockerfile
    environment:
      DATABASE_PORT: 3306
      DATABASE_HOST: mysql
      DATABASE_NAME: test
      DATABASE_USER: root
      DATABASE_PASSWORD: root
      DATABASE_POOL_MIN: 1
      DATABASE_POOL_MAX: 1
      REDIS_URL: redis://redis_db:6379
    depends_on:
      mysql:
        condition: service_healthy
  mysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: test
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 5s
      retries: 12
  redis_db:
    image: redis:5.0